GOTO/src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;


/**
 * @ORM\Entity(repositoryClass=LieuRepository::class)
 */
class Lieu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Menu;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive
     */
    private $Budget;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="lieus")
     */
    private $categorie;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="lieu",cascade={"all"},orphanRemoval=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getMenu(): ?string
    {
        return $this->Menu;
    }

    public function setMenu(string $Menu): self
    {
        $this->Menu = $Menu;

        return $this;
    }

    public function getBudget(): ?float
    {
        return $this->Budget;
    }

    public function setBudget(float $Budget): self
    {
        $this->Budget = $Budget;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setLieu($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getLieu() === $this) {
                $reservation->setLieu(null);
            }
        }

        return $this;
    }

    public static function loadValidatorMetadabudget(ClassMetadata $metadata){
        $metadata->addPropertyConstraints('income',new Assert\Positive());
    }

}

GOTO/src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\DateType;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\Column(type="time")
     */
    private $Heure;

    /**
     * @ORM\Column(type="integer")
     *  @Assert\Positive
     */
    private $Nbrpersonnes;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Vip;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $Nbrbebes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Statut;

    /**
     * @ORM\ManyToOne(targetEntity=Lieu::class, inversedBy="reservations")
     */
    private $lieu;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getHeure(): ?\DateTimeInterface
    {
        return $this->Heure;
    }

    public function setHeure(\DateTimeInterface $Heure): self
    {
        $this->Heure = $Heure;

        return $this;
    }

    public function getNbrpersonnes(): ?int
    {
        return $this->Nbrpersonnes;
    }

    public function setNbrpersonnes(int $Nbrpersonnes): self
    {
        $this->Nbrpersonnes = $Nbrpersonnes;

        return $this;
    }

    public function getVip(): ?bool
    {
        return $this->Vip;
    }

    public function setVip(bool $Vip): self
    {
        $this->Vip = $Vip;

        return $this;
    }

    public function getNbrbebes(): ?int
    {
        return $this->Nbrbebes;
    }

    public function setNbrbebes(int $Nbrbebes): self
    {
        $this->Nbrbebes = $Nbrbebes;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->lieu;
    }

    public function setLieu(?Lieu $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }
    public static function loadValidatorMetadanombrebebe(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraints('siblings', new Assert\PositiveOrZero());
    }
    public static function loadValidatorMetadanombrepersonne(ClassMetadata $metadata){
        $metadata->addPropertyConstraints('income',new Assert\Positive());
    }
    /*public static function loadValidatorMetadataDate(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraints('Date', new Assert\GreaterThanOrEqual('22-02-22'));
    }
    */

}

GOTO/src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Lieu;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Date')
            ->add('Heure')
            ->add('Nbrpersonnes')
            ->add('Vip')
            ->add('Nbrbebes')
            ->add('Statut',ChoiceType::class,[
                'choices' => [
                    'En Attente' => 'En Attente',
                    'Confirmée' => 'Confirmée',
                    'Annulée' => 'Annulée',
                ],
                'empty_data' => 'En Attente',
            ])
            ->add('lieu',EntityType::class,[
                'class'=>Lieu::class,
                'choice_label'=>'nom'

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

GOTO/src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\AdminReservationType;
use App\Form\ClientReservationType;
use App\Form\ReservationType;
use App\Repository\LieuRepository;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ReservationController extends AbstractController
{
    /**
     * @Route("/reservation", name="reservation")
     */
    public function index(): Response
    {
        return $this->render('reservation/index.html.twig', [
            'controller_name' => 'ReservationController',
        ]);
    }

    /**
     * @param ReservationRepository $repository
     * @return Response
     * @Route ("/AdminAfficheR",name="AdminAfficheR")
     */
    public function AfficheR(ReservationRepository $repository){
        $reservation=$repository->findAll();
        return $this->render('reservation/AdminAfficheR.html.twig',
        ['reservation'=>$reservation]);
    }


    /**
     * @param ReservationRepository $repository
     * @return Response
     * @Route ("/ClientAfficheR",name="ClientAfficheR")
     */
    public function ClientAfficheR(ReservationRepository $repository){
       $reservation=$repository->findAll();
       return $this->render('reservation/ClientAfficheR.html.twig',
       ['reservation'=>$reservation]);
    }

    /**
     * @param $id
     * @param ReservationRepository $repository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route ("/DeleteR/{id}",name="dR")
     */
    public function DeleteR($id,ReservationRepository $repository){
        $reservation = $repository->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($reservation);
        $em->flush();
        return $this->redirectToRoute('ClientAfficheR');

    }

    /**
     * @param $id
     * @param ReservationRepository $repository
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route ("/AdminDeleteR/{id}",name="AdR")
     */
    public function AdminDeleteR($id,ReservationRepository $repository){
        $reservation = $repository->find($id);
        $em=$this->getDoctrine()->getManager();
        $em->remove($reservation);
        $em->flush();
        return $this->redirectToRoute('AdminAfficheR');

    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @Route("reservation/AdminAddR",name="AdminAddR")
     */
  function AddR(Request $request){
   $reservation=new Reservation();
   $form=$this->createForm(ReservationType::class,$reservation);
   $form->add('Ajouter',SubmitType::class);
   $form->handleRequest($request);
   if($form->isSubmitted() && $form->isValid()){
       $em=$this->getDoctrine()->getManager();
       $em->persist($reservation);
       $em->flush();
       return $this->redirectToRoute('AdminAfficheR');
   }
   return $this->render('reservation/AdminAddR.html.twig',[
       'f'=>$form->createView()
   ]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @Route ("reservation/ClientAddR",name="ClientAddR")
     */
    function ClientAddR(Request $request){
      $reservation=new Reservation();
      $form=$this->createForm(ClientReservationType::class,$reservation);
      $form->add('Ajouter',SubmitType::class);
      $form->handleRequest($request);
      if($form->isSubmitted() && $form->isValid()){
          $em=$this->getDoctrine()->getManager();
          $em->persist($reservation);
          $em->flush();
          return $this->redirectToRoute('ClientAfficheR');
      }
      return $this->render('reservation/ClientAddR.htm.twig',[
          'f'=>$form->createView()
      ]);
    }


   /**
    * @Route ("reservation/UpdateR/{id}",name="updateR")
    */
    function UpdateR(ReservationRepository $repository,Request $request,$id){
       $reservation=$repository->find($id);
       $form=$this->createForm(ReservationType::class,$reservation);
       $form->add('Update',SubmitType::class);
       $form->handleRequest($request);
       if($form->isSubmitted() && $form->isValid()){
           $em=$this->getDoctrine()->getManager();
           $em->flush();
           return $this->redirectToRoute("ClientAfficheR");
       }
       return $this->render('reservation/UpdateR.html.twig',
       [
           'f'=>$form->createView()
       ]);

    }

    /**
     * @Route ("reservation/AdminUpdateR/{id}",name="AdminupdateR")
     */

    function AdminUpdateR(ReservationRepository $repository, Request $request, $id)
    {
        $reservation = $repository->find($id);
        $form=$this->createForm(AdminReservationType::class, $reservation);
        $form->add('Update',SubmitType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em=$this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("AdminAfficheR");
        }
        return $this->render('reservation/AdminUpdateR.html.twig',
        [
                'f'=>$form->createView()
        ]);

    }


    /**
     * @Route ("reservation/rechercheR",name="rechercheR")
     */
    function RechercheR(ReservationRepository $repository,Request $request){
        $data=$request->get('searchR');
        $date_find = new \DateTime($data);
        if(empty($data)){
            $reservation=$repository->findAll();
        }else{
            $reservation=$repository->findBy(['Date'=>$date_find]);
        }

        return $this->render('reservation/ClientAfficheR.html.twig',
            [
                'reservation'=>$reservation
            ]);
    }





}

GOTO/templates/reservation/AddR.html.twig
{% extends 'base.html.twig' %}
{% block title %} Ajouter Reservations {% endblock %}
{% block main %}
    <div class="hero_single version_2">
        <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
            <div class="bg_gray pattern" id= "submit">
                <div class="container margin_60_40">
                    <div class="row justify-content-center" align="left">
                        <div class="col-lg-5">
                            <div class="text-center add_bottom_15">
                                <h4>Ajouter une Reservation</h4>
                            </div>
                            <div id="message-register"></div>
                            <form method="post" action="AdminAddR" id="register">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.Date) }}
                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.Heure) }}
                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.Nbrpersonnes,{'label': 'Nbr Personnes' }) }}
                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.Vip,{'label': 'VIP' }) }}
                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.Nbrbebes,{'label': 'Nbr Bébés' }) }}
                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.Statut,{'label': 'Statut' }) }}

                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row ">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form_row(f.lieu,{'label': 'Lieu de Restauration' }) }}
                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            {{ form(f)}}

                                        </div>
                                    </div>
                                </div>
                                <!-- /row -->
                            </form>
                        </div>
                    </div>
                    <!-- /container -->
                </div>
            </div>
        </div>
    </div>


{% endblock %}

GOTO/templates/reservation/AdminAddR.html.twig
{% extends 'admin.html.twig' %}
{% block title %} Goto Bookings {% endblock %}

{% block admin_body %}
<body class="fixed-nav sticky-footer" id="page-top">
{% endblock %}

{% block content %}
    <div class="content-wrapper">
        <div class="container-fluid">
            <!-- Breadcrumbs-->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href={{ asset('#') }}>Dashboard</a>
                </li>
                <li class="breadcrumb-item active">Bookings</li>
            </ol>
            <div class="box_general">
                <div class="header_box">
                    <h2 class="d-inline-block">Ajouter Reservation</h2>
                    <div class="filter">
                        <select name="orderby" class="selectbox">
                            <option value="Any status">Any status</option>
                            <option value="Approved">Approved</option>
                            <option value="Pending">Pending</option>
                            <option value="Cancelled">Cancelled</option>
                        </select>
                    </div>
                </div>
                {# Adam: a charger avec la liste des reservations #}
                <div class="list_general">
                    {# Adam: insert la table  #}

                    <div class="hero_single version_2">
                        <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
                            <div class="bg_gray pattern" id= "submit">
                                <div class="container margin_60_40">
                                    <div class="row justify-content-center" align="left">
                                        <div class="col-lg-5">

                                            <form method="post" action="{{ asset('AdminAfficheR')}}" id="register">
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.Date) }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.Heure) }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.Nbrpersonnes,{'label': 'Nbr Personnes' }) }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.Vip,{'label': 'VIP' }) }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.Nbrbebes,{'label': 'Nbr Bébés' }) }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.Statut,{'label': 'Statut' }) }}

                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row ">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form_row(f.lieu,{'label': 'Lieu de Restauration' }) }}
                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                                <div class="row">
                                                    <div class="col-lg-12">
                                                        <div class="form-group">
                                                            {{ form(f)}}

                                                        </div>
                                                    </div>
                                                </div>
                                                <!-- /row -->
                                            </form>
                                        </div>
                                    </div>
                                    <!-- /container -->
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                    <div class="hero_single inner_pages_2 background-image" data-background="{{ asset('url(img/hero_submit_perso.jpg')}}">
                        <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">
                        </div>
                    </div>

                </div>
            </div>
            <!-- /box_general-->
            <nav aria-label="...">
                <ul class="pagination pagination-sm add_bottom_30">
                    <li class="page-item disabled">
                        <a class="page-link" href="{{ asset('#') }}" tabindex="-1">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="{{ asset('#') }}">1</a></li>
                    <li class="page-item"><a class="page-link" href="{{ asset('#') }}">2</a></li>
                    <li class="page-item"><a class="page-link" href="{{ asset('#') }}">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="{{ asset('#') }}">Next</a>
                    </li>
                </ul>
            </nav>
            <!-- /pagination-->
        </div>
        <!-- /container-fluid-->

    <!-- /container-wrapper-->

{% endblock %}

GOTO/templates/reservation/AfficheR.html.twig
{% extends 'base.html.twig' %}
{% block title %}Afficher Resrvation{% endblock %}

{% block main %}

    <div class="hero_single version_2" >
    <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">   {# <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)"> #}
        <div class="bg_gray pattern" id="submit">
            <div class="container margin_30_40">
                <div class="row justify-content-center">
                    <div class="col-lg-auto">
                        <h2>Liste des Réservations</h2>
                        <form method="post" action="{{ path('rechercheR') }}">
                            <label>Date</label>
                            <input type="text" name="searchR" placeholder="yyyy/mm/jj"><input type="submit" value="Recherche">
                        </form>
                        <br>
                        <table border=1 >
                            <tr>
                                <th>Id</th>
                                <th>Lieu</th>
                                <th>Date</th>
                                <th>Heure</th>
                                <th>Nb Personnes</th>
                                <th>Nb Bebes</th>
                                <th>Vip</th>
                                <th>Statut</th>
                                <th>Delete</th>
                                <th>Update</th>
                            </tr>
                            <tr {% for r in reservation %}>
                                <td>{{ r.id }}</td>
                                <td>{{ r.lieu.nom }}</td>
                                <td>{{ r.date|date('d/m/Y')}}</td>
                                <td>{{ r.heure|date('H:i') }}</td>
                                <td>{{ r.nbrpersonnes  }}</td>
                                <td>{{ r.nbrbebes  }}</td>
                                <td>{{ r.vip ? 'Oui': 'Non' }}</td>
                                <td>{{ r.statut  }}</td>
                                <td><a href="{{ path('dR',{'id':r.id}) }}">Delete</a></td>
                                <td><a href="{{ path('updateR',{'id':r.id}) }}">Update</a></td>
                            <tr {% endfor %}
                            </tr>
                        </table>

                        <td><a href="{{ path('AddR')}}">Add</a></td>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

GOTO/templates/reservation/ClientAfficheR.html.twig
{% extends 'base.html.twig' %}
{% block title %}Afficher Resrvation{% endblock %}

{% block main %}

    <div class="hero_single version_2" >
    <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)">   {# <div class="opacity-mask" data-opacity-mask="rgba(0, 0, 0, 0.6)"> #}
        <div class="bg_gray pattern" id="submit">
            <div class="container margin_30_40">
                <div class="row justify-content-center">
                    <div class="col-lg-auto">
                        <h2>Mes Réservations</h2>
                        <form method="post" action="{{ path('rechercheR') }}">
                            <label>Date</label>
                            <input type="text" name="searchR" placeholder="yyyy/mm/jj"><input type="submit" value="Recherche">
                        </form>
                        <br>
                        <table border=1 >
                            <tr>
                                <th>Id</th>
                                <th>Lieu</th>
                                <th>Date</th>
                                <th>Heure</th>
                                <th>Nb Personnes</th>
                                <th>Nb Bebes</th>
                                <th>Vip</th>
                                <th>Statut</th>
                                <th>Delete</th>
                                <th>Update</th>
                            </tr>
                            <tr {% for r in reservation %}>
                                <td>{{ r.id }}</td>
                                <td>{{ r.lieu.nom }}</td>
                                <td>{{ r.date|date('d/m/Y')}}</td>
                                <td>{{ r.heure|date('H:i') }}</td>
                                <td>{{ r.nbrpersonnes  }}</td>
                                <td>{{ r.nbrbebes  }}</td>
                                <td>{{ r.vip ? 'Oui': 'Non' }}</td>
                                <td>{{ r.statut  }}</td>
                                <td><a href="{{ path('dR',{'id':r.id}) }}">Delete</a></td>
                             <td><a href="{{ path('updateR',{'id':r.id}) }}">Update</a></td>
                            <tr {% endfor %}
                            </tr>
                        </table>

                        <td><a href="{{ path('ClientAddR')}}">Add</a></td>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}